nelmio_api_doc:
    documentation:
        info:
            title: Popularity score
            description: This is a system that calculates the popularity of a particular word.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/score # Accepts routes under /api except /api/doc
